services:
  - name: hrms-backend
    type: web
    env: docker
    repo: https://github.com/vikasprajapat2/HRMS
    branch: main
    plan: free
    dockerfilePath: Dockerfile
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
